# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNcYYrnv1l0ktWNdNV21U-MPlk7lj6oD
"""

# Install first:
# !pip install "transformers[torch]" accelerate

from transformers import pipeline

# Small open-source chat model; possibly will take a long time to download
chatbot = pipeline(
    "text-generation",
    model="HuggingFaceTB/SmolLM2-360M-Instruct",
    device_map="auto"
)

chatbot = pipeline(
    "text-generation",
    model="HuggingFaceTB/SmolLM2-360M-Instruct",
    device_map="auto"
)

personality = """
You are NewsroomBot, a friendly AI assistant for journalism students.
Explain things clearly, avoid jargon, and give practical examples.
Keep answers short unless asked for more detail.
"""

messages = [
    {"role": "system", "content": personality}
]

def ask_bot(user_text, temperature=0.7):
    messages.append({"role": "user", "content": user_text})

    response = chatbot(
        messages,
        max_new_tokens=150,
        temperature=temperature,
        do_sample=True,
        return_full_text=False
    )

    answer = response[0]["generated_text"]
    messages.append({"role": "assistant", "content": answer})

    return answer

print("Mini chatbot started. Type 'quit' to stop.\n")

while True:
    user_input = input("You: ")

    if user_input.lower() in ["quit", "exit"]:
        break

    temp = input("Temperature? Try 0.2, 0.7, or 1.0: ")
    temp = float(temp) if temp.strip() else 0.7

    answer = ask_bot(user_input, temperature=temp)
    print("\nBot:", answer, "\n")